# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable', models.DecimalField(decimal_places=2, max_digits=11)),
                ('surplus', models.DecimalField(decimal_places=2, max_digits=11)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.Law')),
            ],
        ),
        migrations.AddField(
            model_name='calculation',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.Tax'),
        ),
    ]
