# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0002_auto_20161101_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='short_name',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
