# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_tax_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='short_name',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
