# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_auto_20161107_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='determinant',
            name='condition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='determinant',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='rate',
            name='tokens',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='tokens', to='taxes.Token'),
        ),
        migrations.AlterField(
            model_name='raterange',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='raterange',
            name='lower_limit',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='raterange',
            name='upper_limit',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='raterange',
            name='variable_amount',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
