# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0005_auto_20161107_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='tokens',
            field=models.ManyToManyField(blank=True, db_index=True, to='taxes.Token'),
        ),
    ]
