# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('social_reason', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=16)),
                ('start_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=250)),
                ('activity', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=1000)),
                ('abbreviation', models.CharField(max_length=1000)),
                ('assets', models.DecimalField(decimal_places=2, max_digits=11)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=16)),
                ('nrc', models.CharField(max_length=16)),
                ('registration_date', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributors.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=100)),
                ('other_surnames', models.CharField(max_length=500)),
                ('dui', models.CharField(max_length=10)),
                ('nit', models.CharField(max_length=16)),
                ('birthdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=1000)),
                ('avgRent', models.DecimalField(decimal_places=2, max_digits=11)),
                ('block', models.CharField(max_length=5)),
                ('cnrPlot', models.CharField(max_length=15)),
                ('cnrSector', models.CharField(max_length=15)),
                ('constructedArea', models.DecimalField(decimal_places=2, max_digits=11)),
                ('constructionQa', models.DecimalField(decimal_places=2, max_digits=11)),
                ('coordinateX', models.CharField(max_length=15)),
                ('coordinateY', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=1)),
                ('electricityCompany', models.CharField(max_length=15)),
                ('floors', models.IntegerField()),
                ('lighting', models.CharField(max_length=15)),
                ('linearMeters', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('lot', models.CharField(max_length=15)),
                ('nature', models.CharField(max_length=15)),
                ('nic', models.CharField(max_length=15)),
                ('sector', models.CharField(max_length=15)),
                ('totalArea', models.DecimalField(decimal_places=2, max_digits=11)),
                ('type', models.CharField(max_length=15)),
                ('zone', models.CharField(max_length=15)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributors.Company')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributors.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contributors.Person'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.Person'),
        ),
    ]
