# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='avgRent',
            new_name='avg_rent',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='cnrPlot',
            new_name='cnr_plot',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='cnrSector',
            new_name='cnr_sector',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='constructedArea',
            new_name='constructed_area',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='constructionQa',
            new_name='construction_qa',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='coordinateX',
            new_name='coordinate_x',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='coordinateY',
            new_name='coordinate_y',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='electricityCompany',
            new_name='electricity_company',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='linearMeters',
            new_name='linear_meters',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='totalArea',
            new_name='total_area',
        ),
    ]
